version: 2

models:
  - name: trf_investidores
    description: "Transformação final dos dados de investidores"
    columns:
      - name: codigo_investidor
        tests:
          - not_null
          - unique

      - name: idade
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 300

      - name: tempo_conta_anos
        columns: 
          - name: tempo_conta_anos
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100

      - name: pais_investidor
        tests:
          - accepted_values:
              values: ['brasil']

      - name: Situacao_conta
        tests:
          - accepted_values:
              values: ['ativa', 'inativa', 'outro']

      - name: operou_12_meses
        tests:
          - accepted_values:
              values: ['sim', 'não', 'outro']


